source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target "AcronymFinder" do
pod 'AFNetworking', '~> 2.0'
pod 'MBProgressHUD', '~> 1.0.0'
end

target "AcronymFinderTests" do
    pod 'AFNetworking', '~> 2.0'
    pod 'MBProgressHUD', '~> 1.0.0'
end